apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: register-app
  template:
    metadata:
      labels:
        app: register-app
    spec:
      containers:
        - name: register-app
          image: vishalsharma09/fashion-signup-app:1.0.0-48
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: register-app-db
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: register-app-db
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: register-app-db
                  key: DB_PASSWORD
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: register-app-db
                  key: ADMIN_TOKEN
          ports:
            - containerPort: 8080
